trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

- script: dotnet restore
  workingDirectory: blazor

- script: dotnet build --no-restore
  workingDirectory: blazor

- script: dotnet publish -o out
  workingDirectory: blazor

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'blazor/out'
    artifact: 'binaries'
    publishLocation: 'pipeline'